name: elusive
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pyyaml
  - matplotlib
  - scipy
  - future
  - pip
  - pytorch==1.11
  - tqdm=4.64
  - faiss=1.7.2
  - faiss-cpu=1.7.2
  - pillow=7.2.0
  - torchvision=0.12
  - ipywidgets=7.7.0
  - ipython=8.2.0
  - jupyter=1.0.0
  - jupyter_client=7.2.2
  - jupyter_console=6.4.3
  - jupyter_core=4.9.2

