name: elusive 
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pyyaml
  - matplotlib
  - scipy
  - future
  - pip
  - faiss=1.7.2
  - faiss-cpu=1.7.2
  - pytorch=1.9.0
  - pillow=7.2.0

