Train:
  batch_size: 16
  learning_rate: 0.001
  reg: 0.0005
  epochs: 20
  momentum: .9
  validevery: 100
  train_path: 'dataset/flowers/train'
  test_path: 'dataset/flowers/test'
  val_path: 'dataset/flowers/test'
  optimizer: 'adam'
  pretrained_path: 'MLPMixer/Mixer-B_16.npz'
  data_size: 768


network:
  model: 'MLPMixer'
  category: 'Mixer-B_16-21k'
  pretrain: True

data:
  data: 'dataset/flowers'
  img_h: 224
  img_w: 224
  
loss:
  loss_type: 'TripletLoss'

dataset:
  dataset: 'TripletData'

Misc:
  # Supported log levels: critical, error, warning, info, debug
  loglevel: 'debug'
  logdir: 'logs'