Train:
  batch_size: 256
  learning_rate: 0.0001
  reg: 0.05
  epochs: 25
  momentum: .9
  validevery: 100
  train_path: 'dataset/flowers/train'
  test_path: 'dataset/flowers/test'
  val_path: 'dataset/flowers/test'
  optimizer: 'adam'
  data_size: 1000

network:
  model: 'SiameseNet'
  category: 'resnet18'
  pretrain: False

data:
  data: 'dataset/flowers'
  img_h: 384
  img_w: 384
  faiss_db: 'siamesedb'
  save_db: True
  
loss:
  loss_type: 'ContrastiveLoss'
  # used for contrastive loss only
  loss_margin: 1.0

dataset:
  dataset: 'TripletData'

Misc:
  # Supported log levels: critical, error, warning, info, debug
  loglevel: 'info'
  logdir: 'logs'