Train:
  batch_size: 16
  learning_rate: 0.001
  reg: 0.0005
  epochs: 50
  momentum: .9

network:
  model: 'ResNet'

data:
  data: 'dataset/flowers'
loss:
  loss_type: 'TripletLoss'

dataset:
  dataset: 'TripletData'