Train:
  batch_size: 32
  learning_rate: 0.1
  reg: 0.0005
  epochs: 10
  momentum: .9

network:
  model: 'ResNet'

data:
  data: 'dataset/flowers'
loss:
  loss_type: 'TripletLoss'

dataset:
  dataset: 'TripletData'