Train:
  img_size: 224
  cats: 20
#  batch_size: 32
  batch_size: 12
  learning_rate: 0.1
  reg: 0.0005
  epochs: 10
  optimizer: 'adam'
  momentum: 0.9

network:
  model: 'ResNet'

data:
  folder: 'data'
  dataset: 'TripletData'

loss:
  loss: 'TripletLoss'