Train:
#  batch_size: 32
  batch_size: 8
  learning_rate: 0.01
  reg: 0.0005
  epochs: 100
  momentum: 0.9

network:
  model: 'ResNet'

data:
  folder: 'data'
  dataset: 'TripletData'

loss:
  loss: 'TripletLoss'