Train:
  batch_size: 1
  learning_rate: 0.001
  reg: 0.0005
  epochs: 0
  momentum: .9
  validevery: 100
  train_path: 'dataset/flowers/train'
  test_path: 'dataset/flowers/test'
  val_path: 'dataset/flowers/test'
  optimizer: 'feature_extractor'
  data_size: 1000


network:
  model: 'ViT'

data:
  data: 'dataset/flowers'
  img_h: 384
  img_w: 384
  faiss_db: 'vitdb'
  save_db: True
  
loss:
  loss_type: 'TripletLoss'

dataset:
  dataset: 'TripletData'

Misc:
  # Supported log levels: critical, error, warning, info, debug
  loglevel: 'debug'