Train:
  batch_size: 8
  learning_rate: 0.01
  reg: 0.0005
  epochs: 10
  momentum: .9
  validevery: 100
  train_path: 'dataset/dogs/train'
  test_path: 'dataset/dogs/test'
  val_path: 'dataset/dogs/test'
  optimizer: 'feature_extractor'
  data_size: 1000


network:
  model: 'ViT'

data:
  data: 'dataset/flowers'
  img_h: 224
  img_w: 224
  faiss_db: 'vitdb'
  save_db: True
  
loss:
  loss_type: 'TripletLoss'

dataset:
  dataset: 'TripletData'

Misc:
  # Supported log levels: critical, error, warning, info, debug
  logdir: 'logs'
  loglevel: 'info'